dist: xenial
language: python
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

stages:
  - name: static analysis
  - name: test
  - name: deploy to PyPI
    if: type = push AND tag =~ ^\d+\.\d+\.\d+

jobs:
  include:
    - stage: static analysis
      install: pip install flake8
      script: flake8 wheel tests
      after_success: skip

    - stage: test
      python: pypy2.7-6.0
      env: PYTEST_ADDOPTS="--no-cov"
      after_success: skip

    - stage: test
      python: pypy3.5-6.0
      env: PYTEST_ADDOPTS="--no-cov"
      after_success: skip

    - os: osx
      language: sh
      python: "3.7"
      before_install:
        - brew update
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
      env: HOMEBREW_NO_INSTALL_CLEANUP=1

    - &windows
      stage: test
      os: windows
      language: sh
      python: "2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip

    - <<: *windows
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip

    - stage: test
      dist: trusty
      python: "2.7.3"
      after_success: skip

    - stage: deploy to PyPI
      install: true
      script: skip
      after_success: skip
      deploy:
        provider: pypi
        user: agronholm
        password:
          secure: ea7qVNkcX9+f1jHEPDd6LNY/K6Z5P2PpQVNUaBt/4mhtWXaQ0hnM3I8xl5sOSwE2FYomIDiJh1fFn1ybJctq1T+U5Q94oxEcFBc61nHk6y9jUlQPtQfX5yCbs9+AzX3PVRjt6hWf10sHiU5KPCh1NFwo/6nFxzhb5PzEZJsaqQk+I407XKKIine2PGd9gDdQ5oSIPySCUMo0HT5RFyMaRKWLGlIIk7STJ3SIcPWNPNlKPLqZDJxqCL5jKN0ZkpqfLU5OaSR43bzoY9rM9vlxk4hAYLrZIDnWlfvjLpykQGbIKSujMr4AB/phw0ey3HqcZkQ/EKFrg1Hml959HbrCTUnu2Dv0gyTS5jYEgBTGWxQbSW+y1vuihlB5l9Jbkwa4W+9m3SjYEjvOWva/YxkL0/+pj9txc5ib57F6ETb4yUKPddhZDZp7qDbM0EMLLOgb+zt2JP25T48MNMSYZQ1U7EsEqOZQPqyWIsrM7//wXPl+bssgGvTVML5rEo6ykjxz1veqyQ5JXxe4dpvNtDnb/Ol7lSRxYyL6H/Jy8PqMZZfksWO6aFU8yMw86XoOo6aIPb7Odv6t9yXGmeVD3BlXTbeUTbGkloKHkdsb9GReghp+vEssLdVgj5BMKG4yU0I37GXid15I1OahKNeSor7sQv8Nykjfw7gl5mzzAkGErxg=
        distributions: sdist bdist_wheel
        on:
          tags: true
          repo: pypa/wheel

install: pip install -e .[test]

script: pytest

after_success:
  - pip install codecov
  - codecov --token=acff82f6-e810-47fb-8117-1d23ed9e3078

notifications:
  irc:
    channels:
      - "irc.freenode.net#pypa-dev"
    use_notice: true
    skip_join: true
